### ISSUE TITLE
The transformation configuration between cameras

### ISSUE THREAD

**Issue by q3166** [egauh0113/realsense-tracking-and-depth#1]
Hello, how to calculate the transformation configuration between the two cameras? Thank you！

**Comment by egauh0113** [comment]
There are two common ways to get the information.
1. Attach the cameras' CAD models to the bracket model and get the transformation
2. Perform camera-IMU calibration between two cameras

I recommend the extrinsic calibration using [Kalibr](https://github.com/ethz-asl/kalibr) between IMU in the tracking camera and RGB image of depth camera. Using CAD model to get transformation cannot guarantee the exact extrinsic because of manufacturing errors.
